# Generated by Django 3.1.4 on 2020-12-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20201222_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_toppings', models.JSONField()),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.pizza_size')),
                ('pizza_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.pizza_type')),
            ],
        ),
    ]
