# Generated by Django 3.1.4 on 2020-12-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_user_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pizza',
            name='pizza_toppings',
            field=models.JSONField(default=dict),
        ),
    ]
