# Generated by Django 3.1.4 on 2020-12-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20201222_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_pizza',
            old_name='pizza_size',
            new_name='pizzasizes',
        ),
        migrations.RenameField(
            model_name='user_pizza',
            old_name='pizza_toppings',
            new_name='pizzatoppings',
        ),
        migrations.RenameField(
            model_name='user_pizza',
            old_name='pizza_type',
            new_name='pizzatypes',
        ),
    ]
