# Generated by Django 3.1.4 on 2020-12-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20201222_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_size',
            name='pizza_size',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizza_toppings',
            name='pizza_toppings',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
